services:
  bot-pool-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
    container_name: bot_pool_api
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
    init: true
    restart: unless-stopped
    networks:
      - shared-network

networks:
  shared-network:
    external: true
    name: shared-network
